services:
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdb
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
  web:
    build:
      context: ${PWD}/web
      dockerfile: Dockerfile
    working_dir: /app
    command: >
      bash -lc '
        cd /app &&
        if [ -f package-lock.json ]; then
          npm ci;
        else
          npm install;
        fi &&
        npm run dev -- --host 0.0.0.0 --port 8080
      '
    ports:
      - "80:8080"
    volumes:
      - ${PWD}/web/app:/app
      - /app/node_modules
    tty: true
    environment:
      - NODE_ENV=development


volumes:
  db-storage: